### PR TITLE
Add Chrome Support

### PR DESCRIPTION
**Pull request by pmasucci**
- Add SASS mixins to add browser prefixes to animations
- Change keypress to keydown to trigger animations (keypresses weren't
registering in Chrome on Mac. I'm on bus internet right now so I can't
test if I broke it in Firefox but will update when I can)

### CODE REVIEW

**Comment by pmasucci** [comment]
Ugh. Had it working yesterday but upon inspection today it no longer works in chrome. Sad face.

**Comment by pmasucci** [comment]
OH. I think I got it. :x

**Comment by jennschiffer** [comment]
keydown was still sort of fucked up so i changed it back to keypress but made the marquee triggered by the a key - since my middle name is jean :D thanks so much for helping out!

**Comment by pmasucci** [comment]
Oh man, my middle name is Anthony so now I feel super included. Thanks for taking a look!

**Pull request merged**
